name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 18
      matrix:
#         os: [macOS-10.14, ubuntu-16.04, ubuntu-18.04, windows-2016, windows-2019]
        os: [ubuntu-16.04, ubuntu-18.04, windows-2016]
        python: [ '2.7', '3.4', '3.5', '3.6', '3.7', 'pypy2', 'pypy3' ]
        arch: [ 'x86', 'x64' ]
        exclude:
#         - os: macos-10.14
#           arch: x86
        - os: ubuntu-16.04
          arch: x86
        - os: ubuntu-18.04
          arch: x86
        - os: ubuntu-18.04
          python: 3.4

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}

    - name: Python Version
      run: |
        python --version
