name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [ '2.7', '3.4', '3.5', '3.6', '3.7', 'pypy2', 'pypy3' ]
        arch: [ 'x86', 'x64' ]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}

    - name: Python Version
      run: |
        python --version
